Repository bengreenier/overlayed, pull requests merged in 2018-10, with the labels that each got.

#31 Get correct tray icon for the current platform 🐛
  .bin/build-static.js
  src/electron/assets/images/tray.ico
  src/electron/assets/images/tray.png
  src/electron/assets/images/tray@2x.png
  src/electron/assets/images/trayFull.png
  src/index.ts
Labels: bug

#33 hotfix: no layout data on start 😨
  src/app/main/PluginGrid.tsx
Labels: bug

#32 Error tooltips and logging 🤕
  package-lock.json
  package.json
  src/app/helpers/serialization.tsx
  src/app/main/ErrorBoundry.tsx
  src/app/main/Plugin.tsx
  src/app/main/PluginGrid.tsx
  src/app/main/main.tsx
  src/electron/Bootstrap.ts
  src/electron/CompositeWindow.ts
  src/index.ts
  src/ipc/IPCMessageNames.ts
Labels: enhancement

#49 Default to fullscreen solution to issue #19
  src/electron/Bootstrap.ts
Labels: bug, enhancement, hacktoberfest
