Repository bengreenier/overlayed, pull requests merged in 2018-09, with the labels that each got.

#16 Plugin settings ✨
  src/app/helpers/PluginGrid.tsx
  src/app/helpers/constants.ts
  src/app/helpers/serialization.tsx
  src/app/main/Plugin.tsx
  src/app/main/PluginGrid.tsx
  src/app/main/main.tsx
  src/app/plugin/Clock/ClockPlugin.tsx
  src/app/plugin/IPlugin.ts
  src/app/plugin/Incrementer/IncrementerPlugin.tsx
  src/app/plugin/Incrementer/package.json
  src/app/plugin/Muxy/MuxyAlertsPlugin.tsx
Labels: enhancement, invalid

#24 basic support for safe shutdown 🔋
  src/app/main/PluginGrid.tsx
  src/app/main/main.tsx
  src/app/plugin/Incrementer/IncrementerPlugin.tsx
  src/index.ts
  src/ipc/IPCMessageNames.ts
Labels: bug

#25 support configurable editStyles 🎨
  src/app/main/Plugin.tsx
  src/app/main/PluginGrid.tsx
  src/app/main/main.tsx
  src/electron/CompositeWindow.ts
  src/ipc/IPCMessageNames.ts
Labels: enhancement

#27 Fixed failing build on macOS 🐛
  .bin/build-static.js
  package.json
Labels: bug

#29 adds support for loaded plugin labels 📝
  package-lock.json
  package.json
  src/app/main/Plugin.tsx
  src/app/main/PluginGrid.tsx
Labels: enhancement
